// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pilly-io/metrics-collector/internal/prometheus/client (interfaces: Client)

// Package mock_client is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/prometheus/common/model"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetPodsCPUUsage mocks base method
func (m *MockClient) GetPodsCPUUsage() (model.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPodsCPUUsage")
	ret0, _ := ret[0].(model.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPodsCPUUsage indicates an expected call of GetPodsCPUUsage
func (mr *MockClientMockRecorder) GetPodsCPUUsage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPodsCPUUsage", reflect.TypeOf((*MockClient)(nil).GetPodsCPUUsage))
}

// GetPodsMemoryUsage mocks base method
func (m *MockClient) GetPodsMemoryUsage() (model.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPodsMemoryUsage")
	ret0, _ := ret[0].(model.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPodsMemoryUsage indicates an expected call of GetPodsMemoryUsage
func (mr *MockClientMockRecorder) GetPodsMemoryUsage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPodsMemoryUsage", reflect.TypeOf((*MockClient)(nil).GetPodsMemoryUsage))
}

// GetPodsRequests mocks base method
func (m *MockClient) GetPodsRequests() (model.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPodsRequests")
	ret0, _ := ret[0].(model.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPodsRequests indicates an expected call of GetPodsRequests
func (mr *MockClientMockRecorder) GetPodsRequests() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPodsRequests", reflect.TypeOf((*MockClient)(nil).GetPodsRequests))
}
