apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 013b70c53b0c56e04aafb735936da812757ec319f38d3778e984f6bd1475f0c7
    kubernetes.io/psp: base-logging
  creationTimestamp: "2019-12-23T09:35:54Z"
  generateName: logging-fluentd-fluentd-elasticsearch-
  labels:
    app.kubernetes.io/instance: logging-fluentd
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: fluentd-elasticsearch
    app.kubernetes.io/version: 2.7.0
    controller-revision-hash: 7d67cdc9d8
    helm.sh/chart: fluentd-elasticsearch-4.9.4
    kubernetes.io/cluster-service: "true"
    pod-template-generation: "3"
  name: logging-fluentd-fluentd-elasticsearch-6v8vk
  namespace: logging
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: logging-fluentd-fluentd-elasticsearch
    uid: c44aed50-f4fa-11e9-942d-06c458c24d44
  resourceVersion: "109080198"
  selfLink: /api/v1/namespaces/logging/pods/logging-fluentd-fluentd-elasticsearch-6v8vk
  uid: 9dd8cd13-2567-11ea-a11e-0ab2df5af338
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - ip-172-29-110-42.eu-west-1.compute.internal
  containers:
  - env:
    - name: FLUENTD_ARGS
      value: --no-supervisor -q
    - name: OUTPUT_HOST
      value: efk-master.logging.svc.cluster.local
    - name: OUTPUT_PORT
      value: "9200"
    - name: OUTPUT_PATH
    - name: OUTPUT_USER
      value: elastic
    - name: OUTPUT_PASSWORD
      value: uW54wp99HytUPyEh4AthCrVrcKtYFq
    - name: LOGSTASH_PREFIX
      value: logstash
    - name: OUTPUT_SCHEME
      value: https
    - name: OUTPUT_SSL_VERIFY
      value: "false"
    - name: OUTPUT_SSL_VERSION
      value: TLSv1_2
    - name: OUTPUT_TYPE_NAME
      value: fluentd
    - name: OUTPUT_BUFFER_CHUNK_LIMIT
      value: 2M
    - name: OUTPUT_BUFFER_QUEUE_LIMIT
      value: "8"
    - name: OUTPUT_LOG_LEVEL
      value: info
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: quay.io/fluentd_elasticsearch/fluentd:v2.7.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - |
          LIVENESS_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-300}; STUCK_THRESHOLD_SECONDS=${STUCK_THRESHOLD_SECONDS:-900}; if [ ! -e /var/log/fluentd-buffers ]; then
            exit 1;
          fi; touch -d "${STUCK_THRESHOLD_SECONDS} seconds ago" /tmp/marker-stuck; if [ -z "$(find /var/log/fluentd-buffers -type d -newer /tmp/marker-stuck -print -quit)" ]; then
            rm -rf /var/log/fluentd-buffers;
            exit 1;
          fi; touch -d "${LIVENESS_THRESHOLD_SECONDS} seconds ago" /tmp/marker-liveness; if [ -z "$(find /var/log/fluentd-buffers -type d -newer /tmp/marker-liveness -print -quit)" ]; then
            exit 1;
          fi;
      failureThreshold: 3
      initialDelaySeconds: 600
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 1
    name: logging-fluentd-fluentd-elasticsearch
    resources:
      limits:
        cpu: 100m
        memory: 900Mi
      requests:
        cpu: 100m
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/docker/containers
      name: varlibdockercontainers
      readOnly: true
    - mountPath: /usr/lib64
      name: libsystemddir
      readOnly: true
    - mountPath: /etc/fluent/config.d
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: logging-fluentd-fluentd-elasticsearch-token-hhdqz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-172-29-110-42.eu-west-1.compute.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: logging-fluentd-fluentd-elasticsearch
  serviceAccountName: logging-fluentd-fluentd-elasticsearch
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - hostPath:
      path: /var/log
      type: ""
    name: varlog
  - hostPath:
      path: /var/lib/docker/containers
      type: ""
    name: varlibdockercontainers
  - hostPath:
      path: /usr/lib64
      type: ""
    name: libsystemddir
  - configMap:
      defaultMode: 420
      name: logging-fluentd-fluentd-elasticsearch
    name: config-volume
  - name: logging-fluentd-fluentd-elasticsearch-token-hhdqz
    secret:
      defaultMode: 420
      secretName: logging-fluentd-fluentd-elasticsearch-token-hhdqz
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-12-23T09:35:54Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T07:57:56Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T07:57:56Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-12-23T09:35:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://2bd4f01251be9ba5f66a39e36522723d5fbe1b0a6495c3f20456fb1cd99b4d91
    image: quay.io/fluentd_elasticsearch/fluentd:v2.7.0
    imageID: docker-pullable://quay.io/fluentd_elasticsearch/fluentd@sha256:9d97cc110835d29c77a335475b33a29735892378ff7441f79fad9b9b68cfa149
    lastState:
      terminated:
        containerID: docker://b70815977e79d6aa49ff9a154e0897810ba99ddb83c2888bb9f13cf7cf3cba6c
        exitCode: 1
        finishedAt: "2020-01-22T07:57:54Z"
        reason: Error
        startedAt: "2020-01-21T19:33:18Z"
    name: logging-fluentd-fluentd-elasticsearch
    ready: true
    restartCount: 66
    state:
      running:
        startedAt: "2020-01-22T07:57:56Z"
  hostIP: 172.29.110.42
  phase: Running
  podIP: 100.119.0.3
  qosClass: Burstable
  startTime: "2019-12-23T09:35:54Z"
