apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2020-01-22T17:51:03Z"
  labels:
    controller-uid: 59a49f6b-f560-4b83-a413-7e534226ac9d
    job-name: hello-1579715460
  name: hello-1579715460
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: hello
    uid: c9fcb9c2-17ba-478b-86fd-4e39a8e9138c
  resourceVersion: "316895"
  selfLink: /apis/batch/v1/namespaces/default/jobs/hello-1579715460
  uid: 59a49f6b-f560-4b83-a413-7e534226ac9d
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 59a49f6b-f560-4b83-a413-7e534226ac9d
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 59a49f6b-f560-4b83-a413-7e534226ac9d
        job-name: hello-1579715460
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - date; echo Hello from the Kubernetes cluster
        image: busybox
        imagePullPolicy: Always
        name: hello
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2020-01-22T17:51:06Z"
  conditions:
  - lastProbeTime: "2020-01-22T17:51:06Z"
    lastTransitionTime: "2020-01-22T17:51:06Z"
    status: "True"
    type: Complete
  startTime: "2020-01-22T17:51:03Z"
  succeeded: 1
