apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-01-22T17:51:03Z"
  generateName: hello-1579715460-
  labels:
    controller-uid: 59a49f6b-f560-4b83-a413-7e534226ac9d
    job-name: hello-1579715460
  name: hello-1579715460-jjtvl
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: hello-1579715460
    uid: 59a49f6b-f560-4b83-a413-7e534226ac9d
  resourceVersion: "316894"
  selfLink: /api/v1/namespaces/default/pods/hello-1579715460-jjtvl
  uid: d28a159c-89c2-4c34-8182-fe521eff4fc0
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - date; echo Hello from the Kubernetes cluster
    image: busybox
    imagePullPolicy: Always
    name: hello
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-j2pjj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: localhost.localdomain
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-j2pjj
    secret:
      defaultMode: 420
      secretName: default-token-j2pjj
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T17:51:03Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T17:51:06Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T17:51:06Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T17:51:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://cf25d4c40ba5a16779cca33557e934b0f4ec805a45ea412cfd2f549fd6127520
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:6915be4043561d64e0ab0f8f098dc2ac48e077fe23f488ac24b665166898115a
    lastState: {}
    name: hello
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://cf25d4c40ba5a16779cca33557e934b0f4ec805a45ea412cfd2f549fd6127520
        exitCode: 0
        finishedAt: "2020-01-22T17:51:05Z"
        reason: Completed
        startedAt: "2020-01-22T17:51:05Z"
  hostIP: 192.168.50.62
  phase: Succeeded
  podIP: 10.1.75.19
  podIPs:
  - ip: 10.1.75.19
  qosClass: BestEffort
  startTime: "2020-01-22T17:51:03Z"
