apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: "2020-01-18T10:39:50Z"
  generateName: coredns-9b8997588-
  labels:
    k8s-app: kube-dns
    pod-template-hash: 9b8997588
  name: coredns-9b8997588-7w2ck
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-9b8997588
    uid: d23b1d2c-978a-48aa-89c8-d743e2e022e9
  resourceVersion: "306260"
  selfLink: /api/v1/namespaces/kube-system/pods/coredns-9b8997588-7w2ck
  uid: e0613c80-ca47-47ef-b9e6-792941cbd9f3
spec:
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    image: coredns/coredns:1.5.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: coredns
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    - containerPort: 9153
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8181
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - all
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: coredns-token-kwsjf
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: localhost.localdomain
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns
  serviceAccountName: coredns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: coredns
    name: config-volume
  - name: coredns-token-kwsjf
    secret:
      defaultMode: 420
      secretName: coredns-token-kwsjf
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-18T10:39:52Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T16:39:46Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T16:39:46Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-18T10:39:50Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://05b13b7838f56e9c2fcdb09454f07b5fd8d78185a921e1b5d179c812e77ebb27
    image: docker.io/coredns/coredns:1.5.0
    imageID: docker.io/coredns/coredns@sha256:e83beb5e43f8513fa735e77ffc5859640baea30a882a11cc75c4c3244a737d3c
    lastState:
      terminated:
        containerID: containerd://3e28f86086c25438dbcc8d5a327774bed8fe2cf98e3960ec323e1e3279f520ca
        exitCode: 255
        finishedAt: "2020-01-22T16:39:13Z"
        reason: Unknown
        startedAt: "2020-01-22T16:18:18Z"
    name: coredns
    ready: true
    restartCount: 23
    started: true
    state:
      running:
        startedAt: "2020-01-22T16:39:38Z"
  hostIP: 192.168.50.62
  phase: Running
  podIP: 10.1.75.148
  podIPs:
  - ip: 10.1.75.148
  qosClass: Burstable
  startTime: "2020-01-18T10:39:52Z"
