
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: hello-1579715460
  name: hello-1579715460
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: hello
    uid: c9fcb9c2-17ba-478b-86fd-4e39a8e9138c
  uid: 59a49f6b-f560-4b83-a413-7e534226ac9d
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 59a49f6b-f560-4b83-a413-7e534226ac9d
  template:
    metadata:
      labels:
        controller-uid: 59a49f6b-f560-4b83-a413-7e534226ac9d
        job-name: hello-1579715460
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - date; echo Hello from the Kubernetes cluster
        image: busybox
        imagePullPolicy: Always
        name: hello
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: hola-157971546
  name: hola-157971546
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: hola
    uid: c9fcb9c2-17ba-478b-86fd-4e39a8e9138d
  uid: 59a49f6b-f560-4b83-a413-7e534226ac9e
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 59a49f6b-f560-4b83-a413-7e534226ac9e
  template:
    metadata:
      labels:
        controller-uid: 59a49f6b-f560-4b83-a413-7e534226ac9e
        job-name: hola-157971546
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - date; echo Hola from the Kubernetes cluster
        image: busybox
        imagePullPolicy: Always
        name: hola
        terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
