apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: hola-1579715460
  name: hola-1579715460
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: a33348f1-12c4-427c-bc6b-7ceb4174c92a
  template:
    metadata:
      labels:
        controller-uid: a33348f1-12c4-427c-bc6b-7ceb4174c92a
        job-name: hola-1579715460
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - date; echo hola from the Kubernetes cluster
        image: busybox
        imagePullPolicy: Always
        name: hola
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
